Feature | Refactor code | patricia.corona
patycorona/Couponts pull request #1
Opened 2023-08-02 01:01 UTC by patycorona

Refactor al código en el proyecto Couponts y se utilizó arquitectura clean.

2023-08-02 15:07 UTC, mleyvar commented
Hay que revizar el formato del PR y agregar el archivo README.md para  el comentario/descripcion inicial.

-- Descripcion de la tarea
-- Antecedente ( en caso de)
-- Problema que se esta arreglando (en caso de)
-- Pantallas
-- Resultados de pruebas unitarias /integracion (en caso de)
-- Infomración adicional

Utiliza los estilos y formatos de markdown para github

https://docs.github.com/es/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax

2023-08-02 15:23 UTC, mleyvar commented
Buen trabajo @patycorona :+1: :wave: :wave: :wave:

2023-08-02 19:54 UTC, mleyvar requested changes

2023-08-02 19:54 UTC, mleyvar commented on app/build.gradle
> +//    buildFeatures {
quita los comentarios si ya no los vas a usar

2023-08-02 19:54 UTC, mleyvar commented on app/build.gradle
> +
quitar esta linea

2023-08-02 19:54 UTC, mleyvar commented on app/src/main/java/com/example/couponts/data/database/Extensions.kt
> +fun validateTextCode(code:String):Boolean {
Estas funciones no son propiamente una extensiones, solo son funciones y las puedes meter en una clase de Utils o Tools de uso general

2023-08-02 19:54 UTC, mleyvar commented on app/src/main/java/com/example/couponts/data/model/mapping/GetCuponToModel.kt
> +internal fun CouponEntity.toModel() = CoupontResultModel(
Esta si es una extensión del objeto CouponEntity, esta internal fun.  Las clases no se nombran como Get o Set, esos prefijos se usan para propiedades o metodos, recomiendo cambies el nombre o mejor aun pon la extensión en la clase diseñada para las extensiones del proyecto

2023-08-02 19:54 UTC, mleyvar commented on app/src/main/java/com/example/couponts/AndroidApplication.kt
> +        database = Room.databaseBuilder(
creaste un singleton para crear la instancia de Room, esto si funciona pero lo ideal es meter la creacion de la instancia como lo hicimos con retrofit desde Dagger-Hilt y asi lo metes al grapho de dagger de esta manera ya no necesitas el singleton

2023-08-02 19:54 UTC, mleyvar commented on app/src/main/java/com/example/couponts/data/network/RoomDataBase.kt
> +        AndroidApplication.database.couponDao()
lo que te comenté de meter la instancia en dagger-hilt y asi ya no tienes que crearla de esta forma, la crearias con el @Inject como las demas

2023-08-02 19:54 UTC, mleyvar commented on app/src/main/java/com/example/couponts/data/repository/CouponRepository.kt
> +  suspend fun saveCoupon(couponEntity : CouponEntity):Long
seria setCoupon  utiliza set o get segun el caso

2023-08-02 19:54 UTC, mleyvar commented on app/src/main/java/com/example/couponts/ui/component/Extension.kt
> +
Estas funciones no son extensiones, son funciones de uso general

2023-08-02 21:02 UTC, patycorona commented on app/build.gradle
> +//    buildFeatures {
ya quite los comentarios.

2023-08-06 02:29 UTC, patycorona commented on app/build.gradle
> +
listo.

2023-08-06 02:30 UTC, patycorona commented on app/src/main/java/com/example/couponts/data/database/Extensions.kt
> +fun validateTextCode(code:String):Boolean {
Si ya las coloque en el mismo archivo Utils.

2023-08-06 02:35 UTC, patycorona commented on app/src/main/java/com/example/couponts/data/model/mapping/GetCuponToModel.kt
> +internal fun CouponEntity.toModel() = CoupontResultModel(
Listo.

2023-08-06 02:36 UTC, patycorona commented on app/src/main/java/com/example/couponts/AndroidApplication.kt
> +        database = Room.databaseBuilder(
Ya quedó listo muchas gracias.

2023-08-06 02:37 UTC, patycorona commented on app/src/main/java/com/example/couponts/data/network/RoomDataBase.kt
> +        AndroidApplication.database.couponDao()
listo.

2023-08-06 02:38 UTC, patycorona commented on app/src/main/java/com/example/couponts/data/repository/CouponRepository.kt
> +  suspend fun saveCoupon(couponEntity : CouponEntity):Long
listo.

2023-08-06 02:39 UTC, patycorona commented on app/src/main/java/com/example/couponts/ui/component/Extension.kt
> +
Listo ya integré todas las funciones en un mismo archivo.

2023-08-06 17:29 UTC, mleyvar approved these changes

2023-08-06 22:20 UTC, merged